/**
 * CBC Curriculum Architect Automated CBC Curriculum Book Packager & Marketplace Launch Engine
 * Programmatically generates, structures, packages, and launches CBC learning materials into the ELIB digital bookstore.
 */

import { CBCFullBook } from '../types';

export interface CBCPackagedBookEntry {
  book_id: string;
  title: string;
  category: string;
  tier_level: string;
  subject: string;
  resource_type: string;
  curriculum_standard: string;
  pricing: {
    currency: string;
    amount: number;
  };
  commission_structure: {
    publisher_share: string;
    platform_share: string;
  };
  status: string;
  created_at: string;
}

export interface ELIBLaunchManifest {
  platform: string;
  total_books_packaged: number;
  target_market: string;
  payment_integration: string;
  launch_timestamp: string;
  catalog: CBCPackagedBookEntry[];
}

/**
 * Auto-generate daily 100+ copies/materials to fill the ELIB store catalog for instant M-Pesa purchase.
 */
export function autoGenerateDailyMaterials(): CBCFullBook[] {
  const packager = new CBCBookPackager();
  const catalog = packager.generate_book_catalog();
  return catalog.map(convertPackagedEntryToFullBook);
}

export class CBCBookPackager {
  private curriculum_data = {
    'Pre-Primary': {
      tiers: ['PP1', 'PP2'],
      subjects: [
        'Mathematical Activities',
        'Language Activities',
        'Environmental Activities',
        'Psychomotor and Creative Activities',
        'Religious Education Activities',
      ],
    },
    'Lower Primary': {
      tiers: ['Grade 1', 'Grade 2', 'Grade 3'],
      subjects: [
        'Mathematics',
        'English Language',
        'Kiswahili Language',
        'Environmental Activities',
        'Hygiene and Nutrition Activities',
        'Religious Education',
        'Movement and Creative Activities',
      ],
    },
    'Upper Primary': {
      tiers: ['Grade 4', 'Grade 5', 'Grade 6'],
      subjects: [
        'Mathematics',
        'English',
        'Kiswahili',
        'Science and Technology',
        'Agriculture and Nutrition',
        'Social Studies',
        'Creative Arts',
        'Religious Education',
      ],
    },
    'Junior School': {
      tiers: ['Grade 7', 'Grade 8', 'Grade 9'],
      subjects: [
        'English',
        'Kiswahili',
        'Mathematics',
        'Integrated Science',
        'Health Education',
        'Social Studies',
        'Religious Education',
        'Business Studies',
        'Agriculture',
        'Pre-Technical Studies',
        'Creative Arts and Sports',
      ],
    },
    'Senior School': {
      tiers: ['Grade 10', 'Grade 11', 'Grade 12'],
      pathways: [
        'Arts and Sports Science Pathway',
        'Social Sciences Pathway',
        'STEM Pathway',
      ],
      subjects: [
        'Core English',
        'Core Kiswahili',
        'Physical Education',
        'Community Service Learning',
        'Pathway Specialized Electives',
      ],
    },
  };

  private resource_types = [
    'Curriculum Designs & KICD Guidelines',
    'Teacher Guides & Schemes of Work',
    'Student Course Textbooks',
    'Topical Revision Notes & Worksheets',
    'Assessment Rubrics & CATs',
  ];

  public generate_book_catalog(): CBCPackagedBookEntry[] {
    const catalog: CBCPackagedBookEntry[] = [];
    let book_id_counter = 1001;
    const now = new Date().toISOString().replace('T', ' ').substring(0, 19);

    for (const [tier_name, raw_tier_info] of Object.entries(this.curriculum_data)) {
      const tier_info = raw_tier_info as any;
      if (tier_info.tiers && tier_info.subjects) {
        for (const tier_level of tier_info.tiers) {
          for (const subject of tier_info.subjects) {
            for (const res_type of this.resource_types) {
              const book_entry: CBCPackagedBookEntry = {
                book_id: `ELIB-CBC-${book_id_counter}`,
                title: `${tier_level} ${subject} - ${res_type}`,
                category: tier_name,
                tier_level,
                subject,
                resource_type: res_type,
                curriculum_standard:
                  'Kenya Competency-Based Curriculum (KICD Aligned)',
                pricing: {
                  currency: 'KES',
                  amount: 49.0,
                },
                commission_structure: {
                  publisher_share: '70%',
                  platform_share: '30%',
                },
                status: 'Ready for Marketplace Launch',
                created_at: now,
              };
              catalog.push(book_entry);
              book_id_counter++;
            }
          }
        }
      } else if (tier_info.pathways && tier_info.tiers && tier_info.subjects) {
        for (const tier_level of tier_info.tiers) {
          for (const pathway of tier_info.pathways) {
            for (const subject of tier_info.subjects) {
              const book_entry: CBCPackagedBookEntry = {
                book_id: `ELIB-CBC-${book_id_counter}`,
                title: `${tier_level} ${pathway} - ${subject}`,
                category: 'Senior School',
                tier_level,
                subject,
                resource_type: 'Comprehensive Pathway Module',
                curriculum_standard: 'Kenya Senior School CBC Pathway Framework',
                pricing: {
                  currency: 'KES',
                  amount: 49.0,
                },
                commission_structure: {
                  publisher_share: '70%',
                  platform_share: '30%',
                },
                status: 'Ready for Marketplace Launch',
                created_at: now,
              };
              catalog.push(book_entry);
              book_id_counter++;
            }
          }
        }
      }
    }

    return catalog;
  }

  public package_and_launch(): ELIBLaunchManifest {
    const books = this.generate_book_catalog();

    return {
      platform: 'ELIB Digital Marketplace',
      total_books_packaged: books.length,
      target_market: 'Kenyan Students, Teachers, and Parents',
      payment_integration:
        'M-Pesa STK Push / Till Number (Min 20 KES Wallet Top-up)',
      launch_timestamp: new Date().toISOString(),
      catalog: books,
    };
  }
}

/**
 * Convert a Packaged Catalog Entry into a full CBCFullBook interface for runtime library display.
 */
export function convertPackagedEntryToFullBook(entry: CBCPackagedBookEntry): CBCFullBook {
  return {
    id: entry.book_id,
    title: entry.title,
    grade: entry.tier_level as any,
    subject: entry.subject as any,
    strand: `${entry.category} ${entry.resource_type}`,
    subStrand: `Official KICD Aligned ${entry.subject} Unit`,
    topicPrompt: `Complete official ${entry.tier_level} ${entry.subject} ${entry.resource_type} package`,
    targetAudience: 'Full Book',
    difficultyLevel: 'Standard',
    createdAt: new Date().toISOString(),
    branding: {
      schoolName: 'ELIB DIGITAL BOOKSTORE',
      motto: 'Kenya CBC Quality Education for All',
      teacherName: 'KICD Curriculum Specialist',
      className: `${entry.tier_level} Stream`,
      term: 'Term 1',
      year: '2026',
      coverTheme: 'emerald',
    },
    teacherOverviewNotes: `Official KICD-aligned learning package for ${entry.tier_level} ${entry.subject}. Includes complete curriculum strands, lesson plans, textbook content, and assessment rubrics.`,
    studentSummaryNotes: `Master your ${entry.tier_level} ${entry.subject} studies with this comprehensive ${entry.resource_type} book!`,
    chapters: [
      {
        chapterNumber: 1,
        title: `${entry.subject}: Foundational Concepts & Learning Outcomes`,
        subStrand: `Syllabus Unit 1 - ${entry.subject}`,
        keyInquiryQuestions: [
          `What are the core principles of ${entry.subject} in ${entry.tier_level}?`,
          `How can learners apply ${entry.subject} skills in real-life community situations?`,
          `Why is ${entry.subject} essential for CBC competency development?`,
        ],
        learningOutcomes: {
          knowledge: [
            `Understand foundational terms and concepts in ${entry.tier_level} ${entry.subject}.`,
            `Identify key strands and sub-strands outlined in the KICD syllabus.`,
          ],
          skills: [
            `Apply critical thinking to solve practical problems in ${entry.subject}.`,
            `Conduct collaborative group tasks and inquiry experiments.`,
          ],
          attitudes: [
            `Appreciate the value of ${entry.subject} in daily life and community development.`,
            `Demonstrate responsibility, team integrity, and environmental care.`,
          ],
        },
        coreCompetencies: [
          'Communication and Collaboration',
          'Critical Thinking and Problem Solving',
          'Creativity and Imagination',
          'Digital Literacy',
          'Self-Efficacy',
        ],
        values: ['Responsibility', 'Integrity', 'Patriotism', 'Unity', 'Respect'],
        pertinentIssues: [
          'Environmental Awareness',
          'Health & Financial Literacy',
          'Safety Education',
        ],
        textbookContent: [
          {
            sectionTitle: `1.1 Overview of ${entry.subject} (${entry.tier_level})`,
            bodyMarkdown: `Welcome to **${entry.title}**! This course module provides a structured approach to **${entry.subject}** under the **Kenya Competency-Based Curriculum (CBC)**.

### Core Objectives
1. Develop deep conceptual understanding in **${entry.subject}**.
2. Master practical competencies through hands-on activities and group experiments.
3. Cultivate national values including responsibility, integrity, and patriotism.

> **ELIB Marketplace Note:** This official material is published under **${entry.curriculum_standard}** with 70% publisher royalty distribution and instant M-Pesa access.`,
            keyVocabulary: [
              {
                term: entry.subject.split(' ')[0] || 'Competency',
                definition: `A core concept in ${entry.tier_level} ${entry.subject} syllabus.`,
              },
              {
                term: 'Formative Assessment',
                definition: 'Continuous learning checks to evaluate student progress and provide feedback.',
              },
            ],
            funFacts: [
              `CBC emphasizes practical application of ${entry.subject} rather than rote memorization!`,
            ],
          },
        ],
        lessonPlan: {
          learningResources: [
            'KICD Approved Textbooks',
            'Charts and Digital Tablets',
            'Local Environment Objects',
          ],
          steps: [
            {
              phase: 'Introduction (5 mins)',
              teacherActivities: 'Guide learners through diagnostic starter question on prior knowledge.',
              learnerActivities: 'Brainstorm in pairs and state key real-life applications.',
              assessmentStrategy: 'Oral questioning and baseline observation.',
            },
            {
              phase: 'Lesson Development (25 mins)',
              teacherActivities: 'Explain topic strands with visual illustrations and conduct guided practicals.',
              learnerActivities: 'Work in small teams to complete worksheet activity.',
              assessmentStrategy: 'Peer assessment and checklist rating.',
            },
            {
              phase: 'Conclusion & Reflection (10 mins)',
              teacherActivities: 'Summarize key inquiry questions and assign home-based extended task.',
              learnerActivities: 'Complete exit ticket summary in notebooks.',
              assessmentStrategy: 'Exit slip review.',
            },
          ],
          differentiationNotes: {
            fastLearners: 'Provide enrichment analytical tasks and peer mentoring roles.',
            slowLearners: 'Offer simplified step-by-step guidance and visual flashcards.',
            specialNeeds: 'Ensure accessible materials and extra time during practical tasks.',
          },
          keyVocabulary: [
            {
              term: 'Outcome',
              definition: 'The specific knowledge, skill, or attitude expected after learning.',
            },
          ],
        },
        practicalActivities: [
          {
            title: `Community & Field Practical - ${entry.subject}`,
            type: 'Group Collaboration',
            materialsNeeded: ['Notebooks', 'Locally available learning tools', 'Visual charts'],
            stepByStepGuide: [
              'Form collaborative learning teams of 4-5 students.',
              `Observe and investigate local examples of ${entry.subject} in the school environment.`,
              'Record observations and share findings with peer groups.',
            ],
            expectedOutput: `Summary project report and presentation on ${entry.subject}.`,
            competencyAssessed: 'Communication, Collaboration & Critical Thinking',
          },
        ],
        worksheetQuestions: [
          {
            id: 'wq1',
            type: 'mcq',
            question: `What is a primary objective of studying ${entry.subject} in ${entry.tier_level}?`,
            options: [
              'Developing practical competencies and critical thinking',
              'Relying solely on final examinations',
              'Ignoring community needs',
              'Memorizing definitions without understanding',
            ],
            answer: 'Developing practical competencies and critical thinking',
            explanation: 'CBC focuses on practical competencies and real-world application.',
            points: 2,
          },
        ],
        comprehensionQuiz: [
          {
            id: 1,
            question: `Which core value is emphasized during group tasks in ${entry.subject}?`,
            options: ['Unity and Collaboration', 'Selfishness', 'Dishonesty', 'Carelessness'],
            answer: 'Unity and Collaboration',
            explanation: 'CBC promotes values of unity, respect, and teamwork.',
          },
        ],
        rubric: [
          {
            criterion: `Understanding & Application of ${entry.subject}`,
            levels: {
              exceeding: 'Demonstrates outstanding conceptual mastery and applies skills creatively.',
              meeting: 'Accurately demonstrates core concepts and completes tasks independently.',
              approaching: 'Shows basic understanding but requires occasional teacher guidance.',
              below: 'Requires continuous support and guided remediation.',
            },
          },
        ],
        flashcards: [
          {
            front: `What is the core focus of ${entry.subject}?`,
            back: `Developing practical competencies, values, and knowledge aligned with KICD standards.`,
          },
        ],
      },
    ],
  };
}
